// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyWithPatron;

#nullable disable

namespace StudyWithPatron.migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230331090257_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudyWithPatron.Models.ScoreBombs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("id_bomb")
                        .HasColumnType("integer")
                        .HasColumnName("id_bomb");

                    b.Property<int>("id_user")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<int>("score_bomb")
                        .HasColumnType("integer")
                        .HasColumnName("score_bomb");

                    b.HasKey("id");

                    b.ToTable("Score_bombs");
                });

            modelBuilder.Entity("StudyWithPatron.Models.ScoreUsers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("id_user")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<int>("score_user")
                        .HasColumnType("integer")
                        .HasColumnName("score_user");

                    b.HasKey("id");

                    b.ToTable("ScoreUser");
                });

            modelBuilder.Entity("StudyWithPatron.Models.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
